version: "3"
services:
  maria-db-posterr:
    container_name: maria-db-posterr
    image: docker.io/library/mariadb:10.5
    volumes:
      - database-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_DATABASE: quote_provider_db

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    container_name: alpis-redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight
    container_name: alpis-redisinsight
    volumes:
      - redisinsight:/db
    ports:
      - "8001:8001"

volumes:
  redisinsight:
    driver: local            
  database-data:
    driver: local